alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias gh='git hist '
alias gha='git hist --all '
alias githash='git log --pretty=oneline | head -1 | cut -c1-7'
